name=EVE_esp32
version=0.0.1
author=Pavel
maintainer=Pavel
sentence=High-performance ESP32 driver for Bridgetek EVE BT81x graphics controllers.
paragraph=Layered Bus/Core/UI architecture for ESP32 (Arduino). Supports SPI and Quad-SPI modes, DMA transfers, display list management, bitmap handling, and optimized RAM_G uploads. Designed for BT815/BT816/BT817 (VM816C50A) with clean modular API and high-speed graphics applications.
category=Display
url=https://github.com/PavelSunStar/EVE_esp32
architectures=esp32
license=MIT
depends=
